version: '2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./60-elasticsearch.conf:/etc/sysctl.d/60-elasticsearch.conf:ro
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk-stack-network

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    ports:
      - "5000:5000"
    networks:
      - elk-stack-network
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - elk-stack-network
    depends_on:
      - elasticsearch



volumes:
  esdata1:
    driver: local

networks:
  elk-stack-network:  
