version: '2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
      - cluster.name=docker-cluster
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./sysctl.conf:/etc/sysctl.conf:ro
    networks:
      - esnetwork

volumes:
  esdata:
    driver: local
networks:
  esnetwork:
    driver: bridge
