version: '2'

services:
  logstash:
    image: adityahilman/logstash:cloudwatch-logs-input-6.2.1
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline:ro
      - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    networks:
      - esnetwork

networks:
  esnetwork:
    driver: bridge
